# CrashPy

**Module 5 : Computing with Python** 

Python is a fun language to learn, and really easy to pick up even if you are new to programming. In fact, quite often, Python is easier to pick up if you do not have any programming experience whatsoever. Python is high level programming language, targeted at students and professionals from diverse backgrounds.

Python has two flavors -- Python 2 and Python 3. This set of examples are in Python 3, written and executed in the beautifully simple IDE Jupyter Notebook. Note that Jupyter has set up a `localhost:8888` server to render the notebook in your computer's browser. It can render anything now -- should be fun!

> [Module 1](Module1_DataTypes.ipynb) : Data Types in Python  
> [Module 2](Module2_DataStructures.ipynb) : Data Structures in Python   
> [Module 3](Module3_ConditionLoop.ipynb) : Conditions and Loops in Python   
> [Module 4](Module4_Functions.ipynb) : Functions and Modules in Python   
> **Module 5 : Computing with Python**

---

## Files in Python

Handling files is a pre-requisite for a number of Python computing applications. Hence we learn that first.

In [1]:
# Handling Files in Python
file = open("frost.txt", "r", encoding = "utf8")
print("Name of File : ", file.name)
print("File Closed? : ", file.closed)
print("Opening Mode : ", file.mode)
file.close()  # closing a file is crucial

Name of File :  frost.txt
File Closed? :  False
Opening Mode :  r


In [2]:
# Reading Lines from a File
with open("frost.txt", "r", encoding = "utf8") as file:
    line = file.readline()
    line_count = 1
    while line:
        print("Line {0:2d} \t {1:s}".format(line_count, line.strip()))
        line = file.readline()
        line_count += 1

Line  1 	 Two roads diverged in a yellow wood,
Line  2 	 And sorry I could not travel both
Line  3 	 And be one traveler, long I stood
Line  4 	 And looked down one as far as I could
Line  5 	 To where it bent in the undergrowth;
Line  6 	 
Line  7 	 Then took the other, as just as fair,
Line  8 	 And having perhaps the better claim
Line  9 	 Because it was grassy and wanted wear,
Line 10 	 Though as for that the passing there
Line 11 	 Had worn them really about the same,
Line 12 	 
Line 13 	 And both that morning equally lay
Line 14 	 In leaves no step had trodden black.
Line 15 	 Oh, I kept the first for another day!
Line 16 	 Yet knowing how way leads on to way
Line 17 	 I doubted if I should ever come back.
Line 18 	 
Line 19 	 I shall be telling this with a sigh
Line 20 	 Somewhere ages and ages hence:
Line 21 	 Two roads diverged in a wood, and I,
Line 22 	 I took the one less traveled by,
Line 23 	 And that has made all the difference.


In [3]:
# Reading Lines from a File
with open("frost.txt", "r", encoding = "utf8") as file:
    for line_count, line in enumerate(file):
        print("Line {0:2d} \t {1:s}".format(line_count, line.strip()))

Line  0 	 Two roads diverged in a yellow wood,
Line  1 	 And sorry I could not travel both
Line  2 	 And be one traveler, long I stood
Line  3 	 And looked down one as far as I could
Line  4 	 To where it bent in the undergrowth;
Line  5 	 
Line  6 	 Then took the other, as just as fair,
Line  7 	 And having perhaps the better claim
Line  8 	 Because it was grassy and wanted wear,
Line  9 	 Though as for that the passing there
Line 10 	 Had worn them really about the same,
Line 11 	 
Line 12 	 And both that morning equally lay
Line 13 	 In leaves no step had trodden black.
Line 14 	 Oh, I kept the first for another day!
Line 15 	 Yet knowing how way leads on to way
Line 16 	 I doubted if I should ever come back.
Line 17 	 
Line 18 	 I shall be telling this with a sigh
Line 19 	 Somewhere ages and ages hence:
Line 20 	 Two roads diverged in a wood, and I,
Line 21 	 I took the one less traveled by,
Line 22 	 And that has made all the difference.


In [4]:
# Reading Words from a File
with open("frost.txt", "r", encoding = "utf8") as file:
    for line_count, line in enumerate(file):
        print("Line {0:2d} \t".format(line_count), end = "")
        for word in line.split(" "):
            print(word.strip(), end = "\t")
        print()

Line  0 	Two	roads	diverged	in	a	yellow	wood,	
Line  1 	And	sorry	I	could	not	travel	both	
Line  2 	And	be	one	traveler,	long	I	stood	
Line  3 	And	looked	down	one	as	far	as	I	could	
Line  4 	To	where	it	bent	in	the	undergrowth;	
Line  5 		
Line  6 	Then	took	the	other,	as	just	as	fair,	
Line  7 	And	having	perhaps	the	better	claim	
Line  8 	Because	it	was	grassy	and	wanted	wear,	
Line  9 	Though	as	for	that	the	passing	there	
Line 10 	Had	worn	them	really	about	the	same,	
Line 11 		
Line 12 	And	both	that	morning	equally	lay	
Line 13 	In	leaves	no	step	had	trodden	black.	
Line 14 	Oh,	I	kept	the	first	for	another	day!	
Line 15 	Yet	knowing	how	way	leads	on	to	way	
Line 16 	I	doubted	if	I	should	ever	come	back.	
Line 17 		
Line 18 	I	shall	be	telling	this	with	a	sigh	
Line 19 	Somewhere	ages	and	ages	hence:	
Line 20 	Two	roads	diverged	in	a	wood,	and	I,	
Line 21 	I	took	the	one	less	traveled	by,	
Line 22 	And	that	has	made	all	the	difference.	


---

## Numeric Computation

`NumPy` is one of the most versatile modules in Python. It helps in Numeric and Scientific computations. This library does not come with the standard Python installation. If you want to use `NumPy`, install the package using your Python package manager of choice. I prefer Conda : `conda install numpy`.

In [5]:
# Import NumPy
import numpy as np
x = np.array([1, 2, 3, 4, 5])
print(x, "is of type", x.dtype, "and of size", x.size, "with shape", x.shape)

[1 2 3 4 5] is of type int64 and of size 5 with shape (5,)


In [6]:
# Reshape Matrix
x = np.array([1, 2, 3, 4, 5, 6])
x = x.reshape(2,3)
print(x, "is of type", x.dtype, "and of size", x.size, "with shape", x.shape)

[[1 2 3]
 [4 5 6]] is of type int64 and of size 6 with shape (2, 3)


In [7]:
# Array Arithmetic
x = np.arange(1,7).reshape(2,3)
y = np.random.random((2,3))

print(x)
print()
print(y)
print()
print(x + y)

[[1 2 3]
 [4 5 6]]

[[0.12845241 0.1149613  0.1608227 ]
 [0.8786693  0.983979   0.47201309]]

[[1.12845241 2.1149613  3.1608227 ]
 [4.8786693  5.983979   6.47201309]]


In [8]:
# Array Product
x = np.arange(1,7).reshape(2,3)
y = np.random.random((3,2))

print(x)
print()
print(y)
print()
print(x.dot(y))

[[1 2 3]
 [4 5 6]]

[[0.18208356 0.14928051]
 [0.01276313 0.11772955]
 [0.60945408 0.59835635]]

[[2.03597204 2.17980865]
 [4.44887432 4.77590786]]


---

## Symbolic Computation

`SymPy` is the Python library for Symbolic Computation. You may install the `SymPy` module using Conda : `conda install sympy`.

In [9]:
# Import SymPy
import sympy as sp
x, y, z = symbols('x y z')
sym_exp = sp.exp(x*y*z)
print(sym_exp, "is of type", type(sym_exp))

ModuleNotFoundError: No module named 'sympy'

In [ ]:
# Symbolic Derivative
x, y, z = symbols('x y z')
sym_exp = sp.exp(x*y*z)
dif_exp = diff(sym_exp, x, y, 2, z, 4)
print("The derivative of", sym_exp, "is", dif_exp)

---

## Data Analysis

Python is currently the language of choice for Data Scientists. Data Analysis in Python requires `NumPy`, `SciPy`, `Pandas`, `MatPlotLib`, and `SeaBorn`.